backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
collections:
  - name: 'homepage'
    label: 'Homepage'
    files:
      - name: 'whatIdo'
        label: 'What I Do'
        file: 'content/home/whatIDo.md'
        fields:
          - {label: 'Body', name: 'body', widget: 'content'}
      - name: 'hero'
        label: 'Hero'
        file: 'content/home/hero.md'
        fields:
          - {label: 'Body', name: 'body', widget: 'content'}
  - name: 'common'
    label: 'Common'
    files:
      - label: 'Footer'
        name: 'footer'
        file: 'content/common/footer.md'
        fields:
          - { label: 'Body', name: 'body', widget: 'content'}



#  - name: 'pages'
#    label: 'Pages'
#    files:
#      - label: 't'
#        name: 't'
#        file: 'content/home.md'
#        fields:
#          - { label: 'Title', name: 'title', widget: 'string'}
#          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
#          - { label: 'Body', name: 'body', widget: 'content'}
#          - label: 'Cats'
#            name: 'cats'
#            widget: list
#            fields:
#              - { label: 'Name', name: 'name', widget: 'string'}
#              - { label: 'Description', name: 'description', widget: 'text'}